from enum import Enum


class DomainExceptionCode(Enum):
    """
    Domain exception codes
    """

    USER_CREDENTIALS_WRONG = "USER_CREDENTIALS_WRONG"
    USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_WITH_NICKNAME_ALREADY_EXISTS = "USER_WITH_NICKNAME_ALREADY_EXISTS"
