"""create recipes table

Revision ID: 031811878407
Revises: 
Create Date: 2022-10-26 13:32:08.835194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "031811878407"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("uuid", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("favourite_amount", sa.Integer(), nullable=False),
        sa.Column("preparation_time", sa.Integer(), nullable=False),
        sa.Column("cover", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipes")
    # ### end Alembic commands ###
