"""add_relationship_between_recipes_users

Revision ID: 5fd85e581309
Revises: 0a786bd8d27c
Create Date: 2022-11-14 19:48:45.471650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5fd85e581309"
down_revision = "0a786bd8d27c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes", sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.create_foreign_key(
        "recipes_owner_id_fkey", "recipes", "users", ["owner_id"], ["uuid"]
    )
    # ### end Alembic commands ###

    op.execute("UPDATE recipes SET owner_id = '00000000-0000-0000-0000-000000000000'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("recipes_owner_id_fkey", "recipes", type_="foreignkey")
    op.drop_column("recipes", "owner_id")
    # ### end Alembic commands ###
